/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Zero Stock API
 * Canteen operations API for census, menus, procurement, receiving, inventory, processing, and delivery.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary List companies
 */
export const companiesControllerListCompaniesBodyCompanyIdMin =
  -9007199254740991;
export const companiesControllerListCompaniesBodyCompanyIdMax = 9007199254740991;

export const companiesControllerListCompaniesBodySortByRegExp = new RegExp(
  '^[A-Za-z_][A-Za-z0-9_]*$',
);
export const companiesControllerListCompaniesBodyPageMax = 9007199254740991;

export const companiesControllerListCompaniesBodyPageSizeMax = 10000;

export const CompaniesControllerListCompaniesBody = zod.strictObject({
  date: zod.string().optional().describe('Date for the request'),
  company_id: zod
    .int()
    .min(companiesControllerListCompaniesBodyCompanyIdMin)
    .max(companiesControllerListCompaniesBodyCompanyIdMax)
    .optional()
    .describe('Company id'),
  name: zod.string().optional().describe('Name filter'),
  sort_by: zod
    .string()
    .regex(companiesControllerListCompaniesBodySortByRegExp)
    .optional()
    .describe('Column name to sort by'),
  sort_order: zod.enum(['asc', 'desc']).optional().describe('Sort order'),
  page: zod
    .int()
    .min(1)
    .max(companiesControllerListCompaniesBodyPageMax)
    .optional()
    .describe('Page number'),
  page_size: zod
    .int()
    .min(1)
    .max(companiesControllerListCompaniesBodyPageSizeMax)
    .optional()
    .describe('Page size'),
  code: zod.string().optional().describe('Company code filter'),
});

export const CompaniesControllerListCompaniesResponse = zod.strictObject({
  result: zod.strictObject({
    page: zod.number().describe('Current page'),
    page_size: zod.number().describe('Page size'),
    total: zod.number().describe('Total records matching the query'),
    list: zod
      .array(
        zod.strictObject({
          id: zod.number().describe('Company id'),
          name: zod.string().describe('Company name'),
          code: zod.string().describe('Company code'),
          contact_person: zod.string().describe('Contact person'),
          phone: zod.string().describe('Phone number'),
          address: zod.string().describe('Address'),
        }),
      )
      .describe('Companies matching the query'),
  }),
  message: zod.string(),
  error: zod.union([
    zod.strictObject({
      status: zod.number().describe('HTTP status code'),
      url: zod.string().describe('Request URL'),
      type: zod
        .enum([
          'BAD_REQUEST',
          'UNAUTHORIZED',
          'FORBIDDEN',
          'NOT_FOUND',
          'CONFLICT',
          'INTERNAL_SERVER_ERROR',
        ])
        .describe('Application error code'),
      details: zod.string().describe('Error details'),
    }),
    zod.null(),
  ]),
});

/**
 * @summary List companies for options
 */
export const CompaniesControllerListCompanyOptionsResponse = zod.strictObject({
  result: zod.array(
    zod.strictObject({
      id: zod.number().describe('Company id'),
      name: zod.string().describe('Company name'),
      code: zod.string().describe('Company code'),
    }),
  ),
  message: zod.string(),
  error: zod.union([
    zod.strictObject({
      status: zod.number().describe('HTTP status code'),
      url: zod.string().describe('Request URL'),
      type: zod
        .enum([
          'BAD_REQUEST',
          'UNAUTHORIZED',
          'FORBIDDEN',
          'NOT_FOUND',
          'CONFLICT',
          'INTERNAL_SERVER_ERROR',
        ])
        .describe('Application error code'),
      details: zod.string().describe('Error details'),
    }),
    zod.null(),
  ]),
});

/**
 * @summary Create company
 */
export const companiesControllerCreateCompanyBodyNameMax = 100;

export const companiesControllerCreateCompanyBodyCodeMax = 20;

export const companiesControllerCreateCompanyBodyContactPersonMax = 50;

export const companiesControllerCreateCompanyBodyPhoneMax = 30;

export const companiesControllerCreateCompanyBodyAddressMax = 200;

export const companiesControllerCreateCompanyBodyRegionsItemIdMin =
  -9007199254740991;
export const companiesControllerCreateCompanyBodyRegionsItemIdMax = 9007199254740991;

export const companiesControllerCreateCompanyBodyRegionsItemNameMax = 50;

export const CompaniesControllerCreateCompanyBody = zod.strictObject({
  name: zod
    .string()
    .min(1)
    .max(companiesControllerCreateCompanyBodyNameMax)
    .describe('Company name'),
  code: zod
    .string()
    .min(1)
    .max(companiesControllerCreateCompanyBodyCodeMax)
    .describe('Company code'),
  contact_person: zod
    .string()
    .max(companiesControllerCreateCompanyBodyContactPersonMax)
    .optional()
    .describe('Contact person'),
  phone: zod
    .string()
    .max(companiesControllerCreateCompanyBodyPhoneMax)
    .optional()
    .describe('Phone number'),
  address: zod
    .string()
    .max(companiesControllerCreateCompanyBodyAddressMax)
    .optional()
    .describe('Address'),
  description: zod.string().optional().describe('Description'),
  regions: zod
    .array(
      zod.strictObject({
        id: zod
          .int()
          .min(companiesControllerCreateCompanyBodyRegionsItemIdMin)
          .max(companiesControllerCreateCompanyBodyRegionsItemIdMax)
          .optional()
          .describe('Region id. Include to update an existing region.'),
        name: zod
          .string()
          .min(1)
          .max(companiesControllerCreateCompanyBodyRegionsItemNameMax)
          .describe('Region name'),
      }),
    )
    .optional()
    .describe('Company regions to create or update'),
});

export const CompaniesControllerCreateCompanyResponse = zod.strictObject({
  result: zod.strictObject({
    id: zod.number().describe('Company id'),
    name: zod.string().describe('Company name'),
    code: zod.string().describe('Company code'),
    contact_person: zod.string().describe('Contact person'),
    phone: zod.string().describe('Phone number'),
    address: zod.string().describe('Address'),
    description: zod.string().describe('Description'),
    regions: zod
      .array(
        zod.strictObject({
          id: zod.number().describe('Region id'),
          name: zod.string().describe('Region name'),
          company_id: zod.number().describe('Company id'),
        }),
      )
      .describe('Company regions'),
  }),
  message: zod.string(),
  error: zod.union([
    zod.strictObject({
      status: zod.number().describe('HTTP status code'),
      url: zod.string().describe('Request URL'),
      type: zod
        .enum([
          'BAD_REQUEST',
          'UNAUTHORIZED',
          'FORBIDDEN',
          'NOT_FOUND',
          'CONFLICT',
          'INTERNAL_SERVER_ERROR',
        ])
        .describe('Application error code'),
      details: zod.string().describe('Error details'),
    }),
    zod.null(),
  ]),
});

/**
 * @summary Get company
 */
export const CompaniesControllerGetCompanyParams = zod.strictObject({
  id: zod.number(),
});

export const CompaniesControllerGetCompanyResponse = zod.strictObject({
  result: zod.strictObject({
    id: zod.number().describe('Company id'),
    name: zod.string().describe('Company name'),
    code: zod.string().describe('Company code'),
    contact_person: zod.string().describe('Contact person'),
    phone: zod.string().describe('Phone number'),
    address: zod.string().describe('Address'),
    description: zod.string().describe('Description'),
    regions: zod
      .array(
        zod.strictObject({
          id: zod.number().describe('Region id'),
          name: zod.string().describe('Region name'),
          company_id: zod.number().describe('Company id'),
        }),
      )
      .describe('Company regions'),
  }),
  message: zod.string(),
  error: zod.union([
    zod.strictObject({
      status: zod.number().describe('HTTP status code'),
      url: zod.string().describe('Request URL'),
      type: zod
        .enum([
          'BAD_REQUEST',
          'UNAUTHORIZED',
          'FORBIDDEN',
          'NOT_FOUND',
          'CONFLICT',
          'INTERNAL_SERVER_ERROR',
        ])
        .describe('Application error code'),
      details: zod.string().describe('Error details'),
    }),
    zod.null(),
  ]),
});

/**
 * @summary Update company
 */
export const CompaniesControllerUpdateCompanyParams = zod.strictObject({
  id: zod.number(),
});

export const companiesControllerUpdateCompanyBodyNameMax = 100;

export const companiesControllerUpdateCompanyBodyCodeMax = 20;

export const companiesControllerUpdateCompanyBodyContactPersonMax = 50;

export const companiesControllerUpdateCompanyBodyPhoneMax = 30;

export const companiesControllerUpdateCompanyBodyAddressMax = 200;

export const companiesControllerUpdateCompanyBodyRegionsItemIdMin =
  -9007199254740991;
export const companiesControllerUpdateCompanyBodyRegionsItemIdMax = 9007199254740991;

export const companiesControllerUpdateCompanyBodyRegionsItemNameMax = 50;

export const CompaniesControllerUpdateCompanyBody = zod.strictObject({
  name: zod
    .string()
    .min(1)
    .max(companiesControllerUpdateCompanyBodyNameMax)
    .describe('Company name'),
  code: zod
    .string()
    .min(1)
    .max(companiesControllerUpdateCompanyBodyCodeMax)
    .describe('Company code'),
  contact_person: zod
    .string()
    .max(companiesControllerUpdateCompanyBodyContactPersonMax)
    .optional()
    .describe('Contact person'),
  phone: zod
    .string()
    .max(companiesControllerUpdateCompanyBodyPhoneMax)
    .optional()
    .describe('Phone number'),
  address: zod
    .string()
    .max(companiesControllerUpdateCompanyBodyAddressMax)
    .optional()
    .describe('Address'),
  description: zod.string().optional().describe('Description'),
  regions: zod
    .array(
      zod.strictObject({
        id: zod
          .int()
          .min(companiesControllerUpdateCompanyBodyRegionsItemIdMin)
          .max(companiesControllerUpdateCompanyBodyRegionsItemIdMax)
          .optional()
          .describe('Region id. Include to update an existing region.'),
        name: zod
          .string()
          .min(1)
          .max(companiesControllerUpdateCompanyBodyRegionsItemNameMax)
          .describe('Region name'),
      }),
    )
    .optional()
    .describe('Company regions to create or update'),
});

export const CompaniesControllerUpdateCompanyResponse = zod.strictObject({
  result: zod.strictObject({
    id: zod.number().describe('Company id'),
    name: zod.string().describe('Company name'),
    code: zod.string().describe('Company code'),
    contact_person: zod.string().describe('Contact person'),
    phone: zod.string().describe('Phone number'),
    address: zod.string().describe('Address'),
    description: zod.string().describe('Description'),
    regions: zod
      .array(
        zod.strictObject({
          id: zod.number().describe('Region id'),
          name: zod.string().describe('Region name'),
          company_id: zod.number().describe('Company id'),
        }),
      )
      .describe('Company regions'),
  }),
  message: zod.string(),
  error: zod.union([
    zod.strictObject({
      status: zod.number().describe('HTTP status code'),
      url: zod.string().describe('Request URL'),
      type: zod
        .enum([
          'BAD_REQUEST',
          'UNAUTHORIZED',
          'FORBIDDEN',
          'NOT_FOUND',
          'CONFLICT',
          'INTERNAL_SERVER_ERROR',
        ])
        .describe('Application error code'),
      details: zod.string().describe('Error details'),
    }),
    zod.null(),
  ]),
});

/**
 * @summary Delete company
 */
export const CompaniesControllerDeleteCompanyParams = zod.strictObject({
  id: zod.number(),
});

export const CompaniesControllerDeleteCompanyResponse = zod.strictObject({
  result: zod.strictObject({
    id: zod.number().describe('Resource id'),
  }),
  message: zod.string(),
  error: zod.union([
    zod.strictObject({
      status: zod.number().describe('HTTP status code'),
      url: zod.string().describe('Request URL'),
      type: zod
        .enum([
          'BAD_REQUEST',
          'UNAUTHORIZED',
          'FORBIDDEN',
          'NOT_FOUND',
          'CONFLICT',
          'INTERNAL_SERVER_ERROR',
        ])
        .describe('Application error code'),
      details: zod.string().describe('Error details'),
    }),
    zod.null(),
  ]),
});

/**
 * @summary List company regions for options
 */
export const CompaniesControllerListCompanyRegionOptionsParams =
  zod.strictObject({
    id: zod.number(),
  });

export const CompaniesControllerListCompanyRegionOptionsResponse =
  zod.strictObject({
    result: zod.array(
      zod.strictObject({
        id: zod.number().describe('Region id'),
        name: zod.string().describe('Region name'),
      }),
    ),
    message: zod.string(),
    error: zod.union([
      zod.strictObject({
        status: zod.number().describe('HTTP status code'),
        url: zod.string().describe('Request URL'),
        type: zod
          .enum([
            'BAD_REQUEST',
            'UNAUTHORIZED',
            'FORBIDDEN',
            'NOT_FOUND',
            'CONFLICT',
            'INTERNAL_SERVER_ERROR',
          ])
          .describe('Application error code'),
        details: zod.string().describe('Error details'),
      }),
      zod.null(),
    ]),
  });
