/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface components {
    schemas: {
        StapleResponseSchema: {
            /**
             * @description Staple id
             * @example 1
             */
            id: number;
            /**
             * @description Staple name
             * @example Rice
             */
            name: string;
            /**
             * @description Unit name
             * @example kg
             */
            unit_name: string;
            /**
             * @description Kilograms per unit
             * @example 1.000
             */
            kg_per_unit: string;
        };
        StapleListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Staples matching the query */
            results: components["schemas"]["StapleResponseSchema"][];
        };
        StapleListSchema: {
            /**
             * @description Staple name search
             * @example rice
             */
            name?: string;
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        OptionResponseSchema: {
            /**
             * @description Resource id
             * @example 1
             */
            id: number;
            /**
             * @description Resource name
             * @example Rice
             */
            name: string;
        };
        StapleUpsertSchema: {
            /**
             * @description Staple id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Staple name
             * @example Rice
             */
            name: string;
            /**
             * @description Unit name
             * @example kg
             */
            unit_name?: string;
            /**
             * @description Kilograms per unit
             * @example 1.000
             */
            kg_per_unit?: string;
        };
        IdResponseSchema: {
            /**
             * @description Resource id
             * @example 1
             */
            id: number;
        };
        MaterialSpecResponseSchema: {
            /**
             * @description Processed material id
             * @example 1
             */
            id: number;
            /**
             * @description Processing method name
             * @example washed
             */
            method_name: string;
        };
        MaterialResponseSchema: {
            /**
             * @description Material id
             * @example 1
             */
            id: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category id
             * @example 1
             */
            category: number;
            /**
             * @description Material category name
             * @example Grains
             */
            category_name: string | null;
            /**
             * @description Yield rate
             * @example 1.00
             */
            yield_rate: string;
            /** @description Processing methods */
            specs: components["schemas"]["MaterialSpecResponseSchema"][];
        };
        MaterialListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Materials matching the query */
            results: components["schemas"]["MaterialResponseSchema"][];
        };
        MaterialListSchema: {
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Material category id filter
             * @example 1
             */
            category?: number;
        };
        MaterialSpecSchema: {
            /**
             * @description Processing method name
             * @example washed
             */
            method_name: string;
        };
        MaterialUpsertSchema: {
            /**
             * @description Material id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category id
             * @example 1
             */
            category: number;
            /**
             * @description Yield rate as decimal string
             * @example 1.00
             */
            yield_rate: string;
            /** @description Processing methods */
            specs?: components["schemas"]["MaterialSpecSchema"][];
        };
        DietPreviewResponseSchema: {
            /**
             * @description Diet id
             * @example 1
             */
            id: number;
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
        };
        DietListSchema: {
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        DietMealSlotDishDetailResponseSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            dish_id: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            dish_name: string;
            /**
             * @description Dish quantity
             * @example 1
             */
            quantity: number;
        };
        DietMealSlotResponseSchema: {
            /**
             * @description Meal slot id
             * @example 1
             */
            id: number;
            /**
             * @description Day of week, Monday=1 through Sunday=7
             * @example 1
             */
            day_of_week: number;
            /**
             * @description Day display value
             * @example Monday
             */
            day_display: string;
            /**
             * @description Meal time
             * @example B
             * @enum {string}
             */
            meal_time: "B" | "L" | "D";
            /**
             * @description Meal display value
             * @example Breakfast
             */
            meal_display: string;
            /** @description Dish ids */
            dishes: number[];
            /** @description Dish names */
            dish_names: string[];
            /** @description Dish details */
            dishes_detail: components["schemas"]["DietMealSlotDishDetailResponseSchema"][];
        };
        DietDetailResponseSchema: {
            /**
             * @description Diet id
             * @example 1
             */
            id: number;
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
            /**
             * @description Staple id
             * @example 1
             */
            staple: number | null;
            /**
             * @description Staple name
             * @example Rice
             */
            staple_name: string | null;
            /** @description Meal slots */
            meal_slots: components["schemas"]["DietMealSlotResponseSchema"][];
        };
        DietCreateSchema: {
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
        };
        DietUpdateSchema: {
            /**
             * @description Diet name
             * @example Regular
             */
            name?: string;
            /**
             * @description Staple id. New diets default to Rice.
             * @example 1
             */
            staple_id?: number;
        };
        DietMealSlotDishSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            dish_id: number;
            /**
             * @description Dish quantity in this slot
             * @example 1
             */
            quantity: number;
        };
        DietMealSlotUpsertSchema: {
            /**
             * @description Day of week, Monday=1 through Sunday=7
             * @example 1
             */
            day_of_week: number;
            /**
             * @description Meal time
             * @example B
             * @enum {string}
             */
            meal_time: "B" | "L" | "D";
            /** @description Dishes in this slot */
            dishes: components["schemas"]["DietMealSlotDishSchema"][];
        };
        DishIngredientResponseSchema: {
            /**
             * @description Dish ingredient id
             * @example 1
             */
            id: number;
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material: number;
            /**
             * @description Raw material name
             * @example Rice
             */
            raw_material_name: string;
            /**
             * @description Processed material id
             * @example null
             */
            processing: number | null;
            /**
             * @description Processing method name
             * @example washed
             */
            processing_name: string;
            /**
             * @description Yield rate
             * @example 1
             */
            yield_rate: number;
            /**
             * @description Net quantity in kg
             * @example 0.150
             */
            net_quantity: string;
        };
        DishResponseSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            id: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            name: string;
            /**
             * @description Seasonings
             * @example salt
             */
            seasonings: string;
            /**
             * @description Cooking method
             * @example Boil noodles and sauce
             */
            cooking_method: string;
            /** @description Dish ingredients */
            ingredients: components["schemas"]["DishIngredientResponseSchema"][];
        };
        DishListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Dishes matching the query */
            results: components["schemas"]["DishResponseSchema"][];
        };
        DishListSchema: {
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example asc
             */
            sort_order?: string;
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Dish name search
             * @example noodles
             */
            name?: string;
        };
        DishIngredientWriteSchema: {
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material: number;
            /**
             * @description Processed material id
             * @example null
             */
            processing?: number | null;
            /**
             * @description Net quantity in kg
             * @example 0.150
             */
            net_quantity: string;
        };
        DishUpsertSchema: {
            /**
             * @description Dish id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            name: string;
            /**
             * @description Seasonings
             * @example salt
             */
            seasonings?: string;
            /**
             * @description Cooking method
             * @example Boil noodles and sauce
             */
            cooking_method?: string;
            /** @description Ingredients to write */
            ingredients_write?: components["schemas"]["DishIngredientWriteSchema"][];
        };
        SupplierMaterialResponseSchema: {
            /**
             * @description Supplier material id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string;
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material: number;
            /**
             * @description Raw material name
             * @example Rice
             */
            raw_material_name: string;
            /**
             * @description Supplier unit name
             * @example bag
             */
            unit_name: string;
            /**
             * @description Kilograms per supplier unit
             * @example 25.000
             */
            kg_per_unit: string;
            /**
             * @description Supplier price
             * @example 50.00
             */
            price: string | null;
            /**
             * @description Notes
             * @example
             */
            notes: string;
        };
        SupplierResponseSchema: {
            /**
             * @description Supplier id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address: string;
            /** @description Supplier material offerings */
            materials: components["schemas"]["SupplierMaterialResponseSchema"][];
        };
        SupplierListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Suppliers matching the query */
            results: components["schemas"]["SupplierResponseSchema"][];
        };
        SupplierListSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Supplier search text
             * @example market
             */
            search?: string;
        };
        SupplierUpsertSchema: {
            /**
             * @description Supplier id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person?: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone?: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address?: string;
        };
        SupplierMaterialListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Supplier-material offerings matching the query */
            results: components["schemas"]["SupplierMaterialResponseSchema"][];
        };
        SupplierMaterialListSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier?: number;
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material?: number;
            /**
             * @description Search text
             * @example rice
             */
            search?: string;
        };
        SupplierMaterialUpsertSchema: {
            /**
             * @description Supplier material id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier: number;
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material: number;
            /**
             * @description Supplier unit name
             * @example bag
             */
            unit_name?: string;
            /**
             * @description Kilograms per supplier unit
             * @example 25.000
             */
            kg_per_unit?: string;
            /**
             * @description Supplier price
             * @example 50.00
             */
            price?: string | null;
            /**
             * @description Notes
             * @example
             */
            notes?: string;
        };
        CensusResponseSchema: {
            /**
             * @description Census row id
             * @example 1
             */
            id: number;
            /**
             * @description Company id
             * @example 1
             */
            company: number;
            /**
             * @description Census date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Region id
             * @example 1
             */
            region: number;
            /**
             * @description Region name
             * @example North Wing
             */
            region_name: string;
            /**
             * @description Diet id
             * @example 1
             */
            diet_category: number;
            /**
             * @description Diet name
             * @example Regular
             */
            diet_category_name: string;
            /**
             * @description Headcount
             * @example 120
             */
            count: number;
        };
        CensusListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Census records matching the query */
            results: components["schemas"]["CensusResponseSchema"][];
        };
        CensusListSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Start date
             * @example 2026-04-01
             */
            start?: string;
            /**
             * @description End date
             * @example 2026-04-30
             */
            end?: string;
            /**
             * @description Region id
             * @example 1
             */
            region_id?: number;
            /**
             * @description Diet id
             * @example 1
             */
            diet_category_id?: number;
        };
        DatedMutationCountResponseSchema: {
            /**
             * @description Number of created rows
             * @example 1
             */
            created: number;
            /**
             * @description Number of updated rows
             * @example 2
             */
            updated: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            date: string;
        };
        CensusItemSchema: {
            /**
             * @description Region id
             * @example 1
             */
            region_id: number;
            /**
             * @description Diet id
             * @example 1
             */
            diet_category_id: number;
            /**
             * @description Headcount
             * @example 120
             */
            count: number;
        };
        CensusUpsertSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Census rows */
            items: components["schemas"]["CensusItemSchema"][];
        };
        ProcurementAvailableSupplierResponseSchema: {
            /**
             * @description Supplier-material id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
        };
        ProcurementPreviewResponseSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            id: number;
            /**
             * @description Procurement date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            material_category: string;
            /**
             * @description Demand in kg
             * @example 20
             */
            demand_kg: number;
            /**
             * @description Demand in supplier units
             * @example 1
             */
            demand_special_unit: number | null;
            /**
             * @description Stock in kg
             * @example 5
             */
            stock_kg: number;
            /**
             * @description Stock in supplier units
             * @example 0.2
             */
            stock_special_unit: number | null;
            /**
             * @description Required purchase quantity in kg
             * @example 15
             */
            required_kg: number;
            /**
             * @description Required purchase quantity in supplier units
             * @example 0.6
             */
            required_special_unit: number | null;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string | null;
            /**
             * @description Supplier price
             * @example 50
             */
            supplier_price: number | null;
            /**
             * @description Supplier unit name
             * @example bag
             */
            supplier_unit: string | null;
            /** @description Available suppliers */
            available_suppliers: components["schemas"]["ProcurementAvailableSupplierResponseSchema"][];
            /**
             * @description Procurement status
             * @example pending
             */
            status: string;
            /**
             * @description Whether the item can be edited
             * @example true
             */
            editable: boolean;
        };
        ProcurementListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Procurement rows matching the query */
            results: components["schemas"]["ProcurementPreviewResponseSchema"][];
        };
        ProcurementListSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Start date
             * @example 2026-04-01
             */
            start?: string;
            /**
             * @description End date
             * @example 2026-04-30
             */
            end?: string;
            /**
             * @description Procurement status
             * @example PENDING
             */
            status?: string;
        };
        ProcurementRecordResponseSchema: {
            /**
             * @description Procurement record id
             * @example 1
             */
            id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            target_date: string;
            /**
             * @description Procurement status
             * @example PENDING
             */
            status: string;
        };
        DateCompanySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        ProcurementUpdateItemSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier material id
             * @example 1
             */
            supplier_id?: number | null;
        };
        ProcurementUpdateSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Item supplier updates */
            items: components["schemas"]["ProcurementUpdateItemSchema"][];
        };
        UpdatedCountResponseSchema: {
            /**
             * @description Number of updated rows
             * @example 2
             */
            updated: number;
        };
        ProcurementSupplierAssignmentSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            item_id: number;
            /**
             * @description Supplier material id
             * @example 1
             */
            supplier_material_id?: number | null;
        };
        ProcurementAssignSuppliersSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Supplier assignments */
            assignments: components["schemas"]["ProcurementSupplierAssignmentSchema"][];
        };
        ProcurementItemResponseSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            id: number;
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material: number;
            /**
             * @description Raw material name
             * @example Rice
             */
            raw_material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            category: string;
            /**
             * @description Demand quantity in kg
             * @example 20.000
             */
            demand_quantity: string;
            /**
             * @description Stock quantity in kg
             * @example 5.000
             */
            stock_quantity: string;
            /**
             * @description Purchase quantity in kg
             * @example 15.000
             */
            purchase_quantity: string;
            /**
             * @description Demand quantity in supplier units
             * @example 1
             */
            demand_unit_qty: number | null;
            /**
             * @description Stock quantity in supplier units
             * @example 0.2
             */
            stock_unit_qty: number | null;
            /**
             * @description Purchase quantity in supplier units
             * @example 0.6
             */
            purchase_unit_qty: number | null;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string | null;
            /**
             * @description Supplier unit name
             * @example bag
             */
            supplier_unit_name: string | null;
            /**
             * @description Kilograms per supplier unit
             * @example 25.000
             */
            supplier_kg_per_unit: string | null;
            /**
             * @description Supplier price
             * @example 50.00
             */
            supplier_price: string | null;
            /**
             * @description Notes
             * @example
             */
            notes: string;
        };
        ProcurementSheetItemResponseSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category
             * @example Grains
             */
            category: string;
            /**
             * @description Demand in kg
             * @example 20
             */
            demand_kg: number;
            /**
             * @description Demand in supplier units
             * @example 1
             */
            demand_unit_qty: number | null;
            /**
             * @description Stock in kg
             * @example 5
             */
            stock_kg: number;
            /**
             * @description Stock in supplier units
             * @example 0.2
             */
            stock_unit_qty: number | null;
            /**
             * @description Purchase quantity in kg
             * @example 15
             */
            purchase_kg: number;
            /**
             * @description Purchase quantity in supplier units
             * @example 0.6
             */
            purchase_unit_qty: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier: string | null;
            /**
             * @description Supplier unit name
             * @example bag
             */
            supplier_unit_name: string | null;
            /**
             * @description Kilograms per supplier unit
             * @example 25
             */
            supplier_kg_per_unit: number | null;
            /**
             * @description Supplier price
             * @example 50
             */
            supplier_price: number | null;
        };
        ProcurementSheetResponseSchema: {
            /**
             * @description Procurement record id
             * @example 1
             */
            id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Day of week
             * @example Tuesday
             */
            day_of_week: string;
            /**
             * @description Company name
             * @example Main Campus
             */
            company: string;
            /**
             * @description Procurement status
             * @example PENDING
             */
            status: string;
            /** @description Sheet items */
            items: components["schemas"]["ProcurementSheetItemResponseSchema"][];
        };
        ReceivingPreviewResponseSchema: {
            /**
             * @description Receiving item id
             * @example 1
             */
            id: number;
            /**
             * @description Received date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            material_category: string;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string | null;
            /**
             * @description Required quantity in kg
             * @example 15
             */
            required_kg: number;
            /**
             * @description Required quantity in supplier units
             * @example 0.6
             */
            required_special_unit: number | null;
            /**
             * @description Actual received quantity in kg
             * @example 15
             */
            actual_received_kg: number;
            /**
             * @description Actual received quantity in supplier units
             * @example 0.6
             */
            actual_received_special_unit: number | null;
            /**
             * @description Receiving status
             * @example pending
             */
            status: string;
            /**
             * @description Whether the row can be edited
             * @example true
             */
            editable: boolean;
        };
        ReceivingListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Receiving rows matching the query */
            results: components["schemas"]["ReceivingPreviewResponseSchema"][];
        };
        ReceivingListSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material or supplier search
             * @example rice
             */
            search?: string;
        };
        ReceivingTemplateItemResponseSchema: {
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material_id: number;
            /**
             * @description Raw material name
             * @example Rice
             */
            raw_material_name: string;
            /**
             * @description Expected quantity in kg
             * @example 15
             */
            expected_quantity: number;
            /**
             * @description Actual quantity in kg
             * @example 15
             */
            actual_quantity: number;
        };
        ReceivingTemplateResponseSchema: {
            /**
             * @description Procurement record id
             * @example 1
             */
            procurement_id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            target_date: string;
            /**
             * @description Receiving status
             * @example PENDING
             */
            status: string;
            /** @description Receiving template items */
            items: components["schemas"]["ReceivingTemplateItemResponseSchema"][];
        };
        ReceivingCreateItemSchema: {
            /**
             * @description Raw material id
             * @example 1
             */
            raw_material_id: number;
            /**
             * @description Actual received quantity in kg
             * @example 10
             */
            actual_quantity: number;
            /**
             * @description Item notes
             * @example
             */
            notes?: string;
        };
        ReceivingUpsertSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Procurement id
             * @example 1
             */
            procurement_id: number;
            /**
             * @description Receiving notes
             * @example
             */
            notes?: string;
            /** @description Received items */
            items: components["schemas"]["ReceivingCreateItemSchema"][];
        };
        ReceivingUpdateItemSchema: {
            /**
             * @description Receiving item id
             * @example 1
             */
            id: number;
            /**
             * @description Actual received kg
             * @example 10
             */
            actual_received_kg: number | null;
            /**
             * @description Actual received supplier units
             * @example null
             */
            actual_received_special_unit?: number | null;
        };
        ReceivingUpdateSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Receiving item updates */
            items: components["schemas"]["ReceivingUpdateItemSchema"][];
        };
        ProcessingItemResponseSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            category: string;
            /**
             * @description Processing method
             * @example washed
             */
            processing_method: string;
            /**
             * @description Required processing quantity
             * @example 12.5
             */
            processing_requirement: number;
            /**
             * @description Processing time
             * @example
             */
            processing_time: string;
        };
        ProcessingListSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Column to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Legacy ordering value
             * @example -date
             */
            ordering?: string;
            /**
             * @description Sort order
             * @example asc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material id
             * @example 1
             */
            material_id?: number;
        };
        ProcessingOrderResponseSchema: {
            /**
             * @description Processing order id
             * @example 1
             */
            id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            target_date: string;
            /**
             * @description Processing order status
             * @example DRAFT
             */
            status: string;
        };
        HealthResponseDto: {
            /** @example ok */
            status: string;
        };
        ApiErrorDto: {
            /** @example 400 */
            status: number;
            /** @example /api/materials */
            url: string;
            /** @example BadRequestException */
            type: string;
            /** @example Validation failed */
            details: string;
        };
        HealthApiResponseSchema: {
            results: components["schemas"]["HealthResponseDto"];
            /** @example success */
            message: string;
            error: components["schemas"]["ApiErrorDto"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type StapleResponseSchema = components['schemas']['StapleResponseSchema'];
export type StapleListResponseSchema = components['schemas']['StapleListResponseSchema'];
export type StapleListSchema = components['schemas']['StapleListSchema'];
export type OptionResponseSchema = components['schemas']['OptionResponseSchema'];
export type StapleUpsertSchema = components['schemas']['StapleUpsertSchema'];
export type IdResponseSchema = components['schemas']['IdResponseSchema'];
export type MaterialSpecResponseSchema = components['schemas']['MaterialSpecResponseSchema'];
export type MaterialResponseSchema = components['schemas']['MaterialResponseSchema'];
export type MaterialListResponseSchema = components['schemas']['MaterialListResponseSchema'];
export type MaterialListSchema = components['schemas']['MaterialListSchema'];
export type MaterialSpecSchema = components['schemas']['MaterialSpecSchema'];
export type MaterialUpsertSchema = components['schemas']['MaterialUpsertSchema'];
export type DietPreviewResponseSchema = components['schemas']['DietPreviewResponseSchema'];
export type DietListSchema = components['schemas']['DietListSchema'];
export type DietMealSlotDishDetailResponseSchema = components['schemas']['DietMealSlotDishDetailResponseSchema'];
export type DietMealSlotResponseSchema = components['schemas']['DietMealSlotResponseSchema'];
export type DietDetailResponseSchema = components['schemas']['DietDetailResponseSchema'];
export type DietCreateSchema = components['schemas']['DietCreateSchema'];
export type DietUpdateSchema = components['schemas']['DietUpdateSchema'];
export type DietMealSlotDishSchema = components['schemas']['DietMealSlotDishSchema'];
export type DietMealSlotUpsertSchema = components['schemas']['DietMealSlotUpsertSchema'];
export type DishIngredientResponseSchema = components['schemas']['DishIngredientResponseSchema'];
export type DishResponseSchema = components['schemas']['DishResponseSchema'];
export type DishListResponseSchema = components['schemas']['DishListResponseSchema'];
export type DishListSchema = components['schemas']['DishListSchema'];
export type DishIngredientWriteSchema = components['schemas']['DishIngredientWriteSchema'];
export type DishUpsertSchema = components['schemas']['DishUpsertSchema'];
export type SupplierMaterialResponseSchema = components['schemas']['SupplierMaterialResponseSchema'];
export type SupplierResponseSchema = components['schemas']['SupplierResponseSchema'];
export type SupplierListResponseSchema = components['schemas']['SupplierListResponseSchema'];
export type SupplierListSchema = components['schemas']['SupplierListSchema'];
export type SupplierUpsertSchema = components['schemas']['SupplierUpsertSchema'];
export type SupplierMaterialListResponseSchema = components['schemas']['SupplierMaterialListResponseSchema'];
export type SupplierMaterialListSchema = components['schemas']['SupplierMaterialListSchema'];
export type SupplierMaterialUpsertSchema = components['schemas']['SupplierMaterialUpsertSchema'];
export type CensusResponseSchema = components['schemas']['CensusResponseSchema'];
export type CensusListResponseSchema = components['schemas']['CensusListResponseSchema'];
export type CensusListSchema = components['schemas']['CensusListSchema'];
export type DatedMutationCountResponseSchema = components['schemas']['DatedMutationCountResponseSchema'];
export type CensusItemSchema = components['schemas']['CensusItemSchema'];
export type CensusUpsertSchema = components['schemas']['CensusUpsertSchema'];
export type ProcurementAvailableSupplierResponseSchema = components['schemas']['ProcurementAvailableSupplierResponseSchema'];
export type ProcurementPreviewResponseSchema = components['schemas']['ProcurementPreviewResponseSchema'];
export type ProcurementListResponseSchema = components['schemas']['ProcurementListResponseSchema'];
export type ProcurementListSchema = components['schemas']['ProcurementListSchema'];
export type ProcurementRecordResponseSchema = components['schemas']['ProcurementRecordResponseSchema'];
export type DateCompanySchema = components['schemas']['DateCompanySchema'];
export type ProcurementUpdateItemSchema = components['schemas']['ProcurementUpdateItemSchema'];
export type ProcurementUpdateSchema = components['schemas']['ProcurementUpdateSchema'];
export type UpdatedCountResponseSchema = components['schemas']['UpdatedCountResponseSchema'];
export type ProcurementSupplierAssignmentSchema = components['schemas']['ProcurementSupplierAssignmentSchema'];
export type ProcurementAssignSuppliersSchema = components['schemas']['ProcurementAssignSuppliersSchema'];
export type ProcurementItemResponseSchema = components['schemas']['ProcurementItemResponseSchema'];
export type ProcurementSheetItemResponseSchema = components['schemas']['ProcurementSheetItemResponseSchema'];
export type ProcurementSheetResponseSchema = components['schemas']['ProcurementSheetResponseSchema'];
export type ReceivingPreviewResponseSchema = components['schemas']['ReceivingPreviewResponseSchema'];
export type ReceivingListResponseSchema = components['schemas']['ReceivingListResponseSchema'];
export type ReceivingListSchema = components['schemas']['ReceivingListSchema'];
export type ReceivingTemplateItemResponseSchema = components['schemas']['ReceivingTemplateItemResponseSchema'];
export type ReceivingTemplateResponseSchema = components['schemas']['ReceivingTemplateResponseSchema'];
export type ReceivingCreateItemSchema = components['schemas']['ReceivingCreateItemSchema'];
export type ReceivingUpsertSchema = components['schemas']['ReceivingUpsertSchema'];
export type ReceivingUpdateItemSchema = components['schemas']['ReceivingUpdateItemSchema'];
export type ReceivingUpdateSchema = components['schemas']['ReceivingUpdateSchema'];
export type ProcessingItemResponseSchema = components['schemas']['ProcessingItemResponseSchema'];
export type ProcessingListSchema = components['schemas']['ProcessingListSchema'];
export type ProcessingOrderResponseSchema = components['schemas']['ProcessingOrderResponseSchema'];
export type HealthResponseDto = components['schemas']['HealthResponseDto'];
export type ApiErrorDto = components['schemas']['ApiErrorDto'];
export type HealthApiResponseSchema = components['schemas']['HealthApiResponseSchema'];
