/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface components {
    schemas: {
        ApiErrorDto: {
            /**
             * @description HTTP status code
             * @example 400
             */
            status: number;
            /**
             * @description Request URL
             * @example /api/materials
             */
            url: string;
            /**
             * @description Application error code
             * @example BAD_REQUEST
             * @enum {string}
             */
            type: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INTERNAL_SERVER_ERROR";
            /**
             * @description Error details
             * @example Validation failed
             */
            details: string;
        };
        ApiResponseDto: {
            /** @description Response payload */
            result: Record<string, never> | null;
            /**
             * @description Response status message
             * @example success
             * @enum {string}
             */
            message: "success" | "error";
            error: components["schemas"]["ApiErrorDto"] | null;
        };
        ApiListResultDto: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Current page records */
            list: unknown[][];
        };
        CompanyPreviewSchema: {
            /**
             * @description Company id
             * @example 1
             */
            id: number;
            /**
             * @description Company name
             * @example Acme Foods
             */
            name: string;
            /**
             * @description Company code
             * @example ACME
             */
            code: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address: string;
        };
        CompanyListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Companies matching the query */
            list: components["schemas"]["CompanyPreviewSchema"][];
        };
        CompanyQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Company code filter
             * @example ACME
             */
            code?: string;
        };
        CompanyOptionSchema: {
            /**
             * @description Company id
             * @example 1
             */
            id: number;
            /**
             * @description Company name
             * @example Acme Foods
             */
            name: string;
            /**
             * @description Company code
             * @example ACME
             */
            code: string;
        };
        CompanyRegionSchema: {
            /**
             * @description Region id
             * @example 1
             */
            id: number;
            /**
             * @description Region name
             * @example North
             */
            name: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id: number;
        };
        CompanyDetailSchema: {
            /**
             * @description Company id
             * @example 1
             */
            id: number;
            /**
             * @description Company name
             * @example Acme Foods
             */
            name: string;
            /**
             * @description Company code
             * @example ACME
             */
            code: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address: string;
            /**
             * @description Description
             * @example Primary client company
             */
            description: string;
            /** @description Company regions */
            regions: components["schemas"]["CompanyRegionSchema"][];
        };
        CompanyRegionUpsertSchema: {
            /**
             * @description Region id. Include to update an existing region.
             * @example 1
             */
            id?: number;
            /**
             * @description Region name
             * @example North
             */
            name: string;
        };
        CompanyUpsertSchema: {
            /**
             * @description Company name
             * @example Acme Foods
             */
            name: string;
            /**
             * @description Company code
             * @example ACME
             */
            code: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person?: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone?: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address?: string;
            /**
             * @description Description
             * @example Primary client company
             */
            description?: string;
            /** @description Company regions to create or update */
            regions?: components["schemas"]["CompanyRegionUpsertSchema"][];
        };
        IdResponseSchema: {
            /**
             * @description Resource id
             * @example 1
             */
            id: number;
        };
        CompanyRegionOptionSchema: {
            /**
             * @description Region id
             * @example 1
             */
            id: number;
            /**
             * @description Region name
             * @example North
             */
            name: string;
        };
        StaplePreviewSchema: {
            /**
             * @description Staple id
             * @example 1
             */
            id: number;
            /**
             * @description Staple name
             * @example Rice
             */
            name: string;
            /**
             * @description Unit name
             * @example g
             */
            unit_name: string;
            /**
             * @description Grams per unit
             * @example 180
             */
            g_per_unit: string;
        };
        StapleListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Staples matching the query */
            list: components["schemas"]["StaplePreviewSchema"][];
        };
        StapleQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        StapleOptionSchema: {
            /**
             * @description Staple id
             * @example 1
             */
            id: number;
            /**
             * @description Staple name
             * @example Rice
             */
            name: string;
        };
        StapleDetailSchema: {
            /**
             * @description Staple id
             * @example 1
             */
            id: number;
            /**
             * @description Staple name
             * @example Rice
             */
            name: string;
            /**
             * @description Unit name
             * @example g
             */
            unit_name: string;
            /**
             * @description Grams per unit
             * @example 180
             */
            g_per_unit: string;
        };
        StapleUpsertSchema: {
            /**
             * @description Staple name
             * @example Rice
             */
            name: string;
            /**
             * @description Unit name
             * @example g
             */
            unit_name?: string;
            /**
             * @description Grams per unit
             * @example 180
             */
            g_per_unit?: string;
        };
        MaterialProcessingMethodSchema: {
            /**
             * @description Material processing method id
             * @example 1
             */
            id: number;
            /**
             * @description Material processing method name
             * @example washed
             */
            name: string;
        };
        MaterialPreviewSchema: {
            /**
             * @description Material id
             * @example 1
             */
            id: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category id
             * @example 1
             */
            category_id: number;
            /**
             * @description Material category name
             * @example Grains
             */
            category_name: string | null;
            /**
             * @description Yield rate
             * @example 1.00
             */
            yield_rate: string;
            /**
             * @description Default supplier-material offering id
             * @example 3
             */
            default_supplier_material_id: number | null;
            /**
             * @description Default supplier id
             * @example 1
             */
            default_supplier_id: number | null;
            /**
             * @description Default supplier name
             * @example Fresh Market
             */
            default_supplier_name: string | null;
            /**
             * @description Processing methods
             * @example [
             *       {
             *         "id": 1,
             *         "name": "washed"
             *       },
             *       {
             *         "id": 2,
             *         "name": "cut"
             *       }
             *     ]
             */
            processing: components["schemas"]["MaterialProcessingMethodSchema"][];
        };
        MaterialListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Materials matching the query */
            list: components["schemas"]["MaterialPreviewSchema"][];
        };
        MaterialQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material category id filter
             * @example 1
             */
            category_id?: number;
        };
        MaterialOptionSchema: {
            /**
             * @description Material id
             * @example 1
             */
            id: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
        };
        MaterialDetailSchema: {
            /**
             * @description Material id
             * @example 1
             */
            id: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category id
             * @example 1
             */
            category_id: number;
            /**
             * @description Material category name
             * @example Grains
             */
            category_name: string | null;
            /**
             * @description Yield rate
             * @example 1.00
             */
            yield_rate: string;
            /**
             * @description Default supplier-material offering id
             * @example 3
             */
            default_supplier_material_id: number | null;
            /**
             * @description Default supplier id
             * @example 1
             */
            default_supplier_id: number | null;
            /**
             * @description Default supplier name
             * @example Fresh Market
             */
            default_supplier_name: string | null;
            /**
             * @description Processing methods
             * @example [
             *       {
             *         "id": 1,
             *         "name": "washed"
             *       },
             *       {
             *         "id": 2,
             *         "name": "cut"
             *       }
             *     ]
             */
            processing: components["schemas"]["MaterialProcessingMethodSchema"][];
        };
        MaterialUpsertSchema: {
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category id
             * @example 1
             */
            category_id: number;
            /**
             * @description Yield rate as decimal string
             * @example 1.00
             */
            yield_rate: string;
            /**
             * @description Processing methods
             * @example [
             *       "washed",
             *       "cut"
             *     ]
             */
            processing?: string[];
        };
        MaterialCategoryOptionSchema: {
            /**
             * @description Material category id
             * @example 1
             */
            id: number;
            /**
             * @description Material category name
             * @example Grains
             */
            name: string;
        };
        DietPreviewSchema: {
            /**
             * @description Diet id
             * @example 1
             */
            id: number;
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
        };
        DietQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        DietOptionSchema: {
            /**
             * @description Diet id
             * @example 1
             */
            id: number;
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
        };
        DietQuantitySchema: {
            /**
             * @description Dish id
             * @example 1
             */
            dish_id: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            dish_name: string;
            /**
             * @description Dish quantity
             * @example 1
             */
            quantity: number;
        };
        DietMealSlotSchema: {
            /**
             * @description Meal slot id
             * @example 1
             */
            id: number;
            /**
             * @description Day of week, Monday=1 through Sunday=7
             * @example 1
             */
            day_of_week: number;
            /**
             * @description Day display value
             * @example Monday
             */
            day_display: string;
            /**
             * @description Meal time
             * @example B
             * @enum {string}
             */
            meal_time: "B" | "L" | "D";
            /**
             * @description Meal display value
             * @example Breakfast
             */
            meal_display: string;
            /** @description Dish ids */
            dishes: number[];
            /** @description Dish names */
            dish_names: string[];
            /** @description Dish details */
            dishes_detail: components["schemas"]["DietQuantitySchema"][];
        };
        DietDetailSchema: {
            /**
             * @description Diet id
             * @example 1
             */
            id: number;
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
            /**
             * @description Staple id
             * @example 1
             */
            staple_id: number | null;
            /**
             * @description Staple name
             * @example Rice
             */
            staple_name: string | null;
            /** @description Meal slots */
            meal_slots: components["schemas"]["DietMealSlotSchema"][];
        };
        DietCreateSchema: {
            /**
             * @description Diet name
             * @example Regular
             */
            name: string;
        };
        DietUpdateSchema: {
            /**
             * @description Diet name
             * @example Regular
             */
            name?: string;
            /**
             * @description Staple id. New diets default to Rice.
             * @example 1
             */
            staple_id?: number;
        };
        DietMealSlotDishSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            dish_id: number;
            /**
             * @description Dish quantity in this slot
             * @example 1
             */
            quantity: number;
        };
        DietMealSlotUpsertSchema: {
            /**
             * @description Day of week, Monday=1 through Sunday=7
             * @example 1
             */
            day_of_week: number;
            /**
             * @description Meal time
             * @example B
             * @enum {string}
             */
            meal_time: "B" | "L" | "D";
            /** @description Dishes in this slot */
            dishes: components["schemas"]["DietMealSlotDishSchema"][];
        };
        DishIngredientSchema: {
            /**
             * @description Dish ingredient id
             * @example 1
             */
            id: number;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material processing method id
             * @example null
             */
            processing_method_id: number | null;
            /**
             * @description Material processing method name
             * @example cut
             */
            processing_method: string | null;
            /**
             * @description Yield rate
             * @example 1
             */
            yield_rate: number;
            /**
             * @description Net quantity in grams
             * @example 150
             */
            net_quantity: string;
        };
        DishPreviewSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            id: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            name: string;
            /**
             * @description Seasonings
             * @example salt
             */
            seasonings: string;
            /**
             * @description Cooking method
             * @example Boil noodles and sauce
             */
            cooking_method: string;
            /** @description Dish ingredients */
            ingredients: components["schemas"]["DishIngredientSchema"][];
        };
        DishListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Dishes matching the query */
            list: components["schemas"]["DishPreviewSchema"][];
        };
        DishQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material id to filter dishes by ingredient
             * @example 1
             */
            material_id?: number;
        };
        DishOptionSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            id: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            name: string;
        };
        DishDetailSchema: {
            /**
             * @description Dish id
             * @example 1
             */
            id: number;
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            name: string;
            /**
             * @description Seasonings
             * @example salt
             */
            seasonings: string;
            /**
             * @description Cooking method
             * @example Boil noodles and sauce
             */
            cooking_method: string;
            /** @description Dish ingredients */
            ingredients: components["schemas"]["DishIngredientSchema"][];
        };
        DishIngredientUpsertSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material processing method id
             * @example null
             */
            processing_method_id?: number | null;
            /**
             * @description Net quantity in grams
             * @example 150
             */
            net_quantity: string;
        };
        DishUpsertSchema: {
            /**
             * @description Dish name
             * @example Tomato noodles
             */
            name: string;
            /**
             * @description Seasonings
             * @example salt
             */
            seasonings?: string;
            /**
             * @description Cooking method
             * @example Boil noodles and sauce
             */
            cooking_method?: string;
            /** @description Ingredients */
            ingredients?: components["schemas"]["DishIngredientUpsertSchema"][];
        };
        SupplierMaterialPreviewSchema: {
            /**
             * @description Supplier material id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Supplier unit name
             * @example bag
             */
            unit_name: string;
            /**
             * @description Grams per supplier unit
             * @example 25000
             */
            g_per_unit: string;
            /**
             * @description Supplier price
             * @example 50.00
             */
            price_per_unit: string | null;
            /**
             * @description Notes
             * @example
             */
            notes: string;
            /**
             * @description Whether this is the default supplier for the material
             * @example true
             */
            isDefaultSupplierMaterial: boolean;
        };
        SupplierPreviewSchema: {
            /**
             * @description Supplier id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address: string;
            /** @description Supplier material offerings */
            materials: components["schemas"]["SupplierMaterialPreviewSchema"][];
        };
        SupplierListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Suppliers matching the query */
            list: components["schemas"]["SupplierPreviewSchema"][];
        };
        SupplierQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material id. Include to list suppliers that supply this material.
             * @example 1
             */
            material_id?: number;
        };
        SupplierOptionSchema: {
            /**
             * @description Supplier-material id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
        };
        SupplierDetailSchema: {
            /**
             * @description Supplier id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address: string;
            /** @description Supplier material offerings */
            materials: components["schemas"]["SupplierMaterialPreviewSchema"][];
        };
        SupplierUpsertSchema: {
            /**
             * @description Supplier id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            name: string;
            /**
             * @description Contact person
             * @example Alice
             */
            contact_person?: string;
            /**
             * @description Phone number
             * @example 555-0100
             */
            phone?: string;
            /**
             * @description Address
             * @example 123 Main St
             */
            address?: string;
        };
        SupplierMaterialListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Supplier-material offerings matching the query */
            list: components["schemas"]["SupplierMaterialPreviewSchema"][];
        };
        SupplierMaterialQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Supplier-material offering id
             * @example 1
             */
            id?: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id?: number;
            /**
             * @description Material id
             * @example 1
             */
            material_id?: number;
        };
        SupplierMaterialOptionSchema: {
            /**
             * @description Supplier material id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier material option name
             * @example Fresh Market - Rice
             */
            name: string;
        };
        SupplierMaterialDetailSchema: {
            /**
             * @description Supplier material id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Supplier unit name
             * @example bag
             */
            unit_name: string;
            /**
             * @description Grams per supplier unit
             * @example 25000
             */
            g_per_unit: string;
            /**
             * @description Supplier price
             * @example 50.00
             */
            price_per_unit: string | null;
            /**
             * @description Notes
             * @example
             */
            notes: string;
            /**
             * @description Whether this is the default supplier for the material
             * @example true
             */
            isDefaultSupplierMaterial: boolean;
        };
        SupplierMaterialUpsertSchema: {
            /**
             * @description Supplier material id. Include to update.
             * @example 1
             */
            id?: number;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Supplier unit name
             * @example bag
             */
            unit_name?: string;
            /**
             * @description Grams per supplier unit
             * @example 25000
             */
            g_per_unit?: string;
            /**
             * @description Supplier price
             * @example 50.00
             */
            price_per_unit?: string | null;
            /**
             * @description Notes
             * @example
             */
            notes?: string;
            /**
             * @description Set to true to mark this offering as the default for its material. Set to false to clear the default. Omit to leave unchanged.
             * @example true
             */
            is_default?: boolean | null;
        };
        CensusPreviewSchema: {
            /**
             * @description Census row id
             * @example 1
             */
            id: number;
            /**
             * @description Company id
             * @example 1
             */
            company_id: number;
            /**
             * @description Census date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Region id
             * @example 1
             */
            region_id: number;
            /**
             * @description Region name
             * @example North Wing
             */
            region_name: string;
            /**
             * @description Diet id
             * @example 1
             */
            diet_category_id: number;
            /**
             * @description Diet name
             * @example Regular
             */
            diet_category_name: string;
            /**
             * @description Headcount
             * @example 120
             */
            count: number;
        };
        CensusListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Census records matching the query */
            list: components["schemas"]["CensusPreviewSchema"][];
        };
        CensusQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Start date
             * @example 2026-04-01
             */
            start?: string;
            /**
             * @description End date
             * @example 2026-04-30
             */
            end?: string;
            /**
             * @description Region id
             * @example 1
             */
            region_id?: number;
            /**
             * @description Diet id
             * @example 1
             */
            diet_category_id?: number;
        };
        DatedMutationCountResponseSchema: {
            /**
             * @description Number of created rows
             * @example 1
             */
            created: number;
            /**
             * @description Number of updated rows
             * @example 2
             */
            updated: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            date: string;
        };
        CensusItemSchema: {
            /**
             * @description Region id
             * @example 1
             */
            region_id: number;
            /**
             * @description Diet id
             * @example 1
             */
            diet_category_id: number;
            /**
             * @description Headcount
             * @example 120
             */
            count: number;
        };
        CensusUpsertSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Census rows */
            items: components["schemas"]["CensusItemSchema"][];
        };
        ProcurementPreviewSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            id: number;
            /**
             * @description Procurement date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            material_category: string;
            /**
             * @description Demand in grams
             * @example 20000
             */
            demand_g: number;
            /**
             * @description Demand in supplier units
             * @example 1
             */
            demand_special_unit: number | null;
            /**
             * @description Stock in grams
             * @example 5000
             */
            stock_g: number;
            /**
             * @description Stock in supplier units
             * @example 0.2
             */
            stock_special_unit: number | null;
            /**
             * @description Required purchase quantity in grams
             * @example 15000
             */
            required_g: number;
            /**
             * @description Required purchase quantity in supplier units
             * @example 0.6
             */
            required_special_unit: number | null;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string | null;
            /**
             * @description Supplier price
             * @example 50
             */
            supplier_price: number | null;
            /**
             * @description Supplier unit name
             * @example bag
             */
            supplier_unit: string | null;
            /** @description Available suppliers */
            available_suppliers: components["schemas"]["SupplierOptionSchema"][];
            /**
             * @description Procurement status
             * @example pending
             */
            status: string;
            /**
             * @description Whether the item can be edited
             * @example true
             */
            editable: boolean;
        };
        ProcurementListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Procurement rows matching the query */
            list: components["schemas"]["ProcurementPreviewSchema"][];
        };
        ProcurementQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Start date
             * @example 2026-04-01
             */
            start?: string;
            /**
             * @description End date
             * @example 2026-04-30
             */
            end?: string;
            /**
             * @description Procurement status
             * @example PENDING
             */
            status?: string;
        };
        ProcurementRecordSchema: {
            /**
             * @description Procurement record id
             * @example 1
             */
            id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            target_date: string;
            /**
             * @description Procurement status
             * @example PENDING
             */
            status: string;
        };
        DateCompanySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        ProcurementUpdateItemSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            id: number;
            /**
             * @description Supplier material id
             * @example 1
             */
            supplier_id?: number | null;
        };
        ProcurementUpdateSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Item supplier updates */
            items: components["schemas"]["ProcurementUpdateItemSchema"][];
        };
        UpdatedCountResponseSchema: {
            /**
             * @description Number of updated rows
             * @example 2
             */
            updated: number;
        };
        ProcurementSupplierAssignmentSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            item_id: number;
            /**
             * @description Supplier material id
             * @example 1
             */
            supplier_material_id?: number | null;
        };
        ProcurementAssignSuppliersSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Supplier assignments */
            assignments: components["schemas"]["ProcurementSupplierAssignmentSchema"][];
        };
        ProcurementItemSchema: {
            /**
             * @description Procurement item id
             * @example 1
             */
            id: number;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            category: string;
            /**
             * @description Demand quantity in grams
             * @example 20000
             */
            demand_quantity: string;
            /**
             * @description Stock quantity in grams
             * @example 5000
             */
            stock_quantity: string;
            /**
             * @description Purchase quantity in grams
             * @example 15000
             */
            purchase_quantity: string;
            /**
             * @description Demand quantity in supplier units
             * @example 1
             */
            demand_unit_qty: number | null;
            /**
             * @description Stock quantity in supplier units
             * @example 0.2
             */
            stock_unit_qty: number | null;
            /**
             * @description Purchase quantity in supplier units
             * @example 0.6
             */
            purchase_unit_qty: number | null;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string | null;
            /**
             * @description Supplier unit name
             * @example bag
             */
            supplier_unit_name: string | null;
            /**
             * @description Grams per supplier unit
             * @example 25000
             */
            supplier_g_per_unit: string | null;
            /**
             * @description Supplier price
             * @example 50.00
             */
            supplier_price: string | null;
            /**
             * @description Notes
             * @example
             */
            notes: string;
        };
        ProcurementSheetItemSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            name: string;
            /**
             * @description Material category
             * @example Grains
             */
            category: string;
            /**
             * @description Demand in grams
             * @example 20000
             */
            demand_g: number;
            /**
             * @description Demand in supplier units
             * @example 1
             */
            demand_unit_qty: number | null;
            /**
             * @description Stock in grams
             * @example 5000
             */
            stock_g: number;
            /**
             * @description Stock in supplier units
             * @example 0.2
             */
            stock_unit_qty: number | null;
            /**
             * @description Purchase quantity in grams
             * @example 15000
             */
            purchase_g: number;
            /**
             * @description Purchase quantity in supplier units
             * @example 0.6
             */
            purchase_unit_qty: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier: string | null;
            /**
             * @description Supplier unit name
             * @example bag
             */
            supplier_unit_name: string | null;
            /**
             * @description Grams per supplier unit
             * @example 25000
             */
            supplier_g_per_unit: number | null;
            /**
             * @description Supplier price
             * @example 50
             */
            supplier_price: number | null;
        };
        ProcurementSheetSchema: {
            /**
             * @description Procurement record id
             * @example 1
             */
            id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Day of week
             * @example Tuesday
             */
            day_of_week: string;
            /**
             * @description Company name
             * @example Main Campus
             */
            company: string;
            /**
             * @description Procurement status
             * @example PENDING
             */
            status: string;
            /** @description Sheet items */
            items: components["schemas"]["ProcurementSheetItemSchema"][];
        };
        ReceivingPreviewSchema: {
            /**
             * @description Receiving item id
             * @example 1
             */
            id: number;
            /**
             * @description Received date
             * @example 2026-04-28
             */
            date: string;
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            material_category: string;
            /**
             * @description Supplier id
             * @example 1
             */
            supplier_id: number | null;
            /**
             * @description Supplier name
             * @example Fresh Market
             */
            supplier_name: string | null;
            /**
             * @description Required quantity in grams
             * @example 15000
             */
            required_g: number;
            /**
             * @description Required quantity in supplier units
             * @example 0.6
             */
            required_special_unit: number | null;
            /**
             * @description Actual received quantity in grams
             * @example 15000
             */
            actual_received_g: number;
            /**
             * @description Actual received quantity in supplier units
             * @example 0.6
             */
            actual_received_special_unit: number | null;
            /**
             * @description Receiving status
             * @example pending
             */
            status: string;
            /**
             * @description Whether the row can be edited
             * @example true
             */
            editable: boolean;
        };
        ReceivingListResponseSchema: {
            /**
             * @description Current page
             * @example 1
             */
            page: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size: number;
            /**
             * @description Total records matching the query
             * @example 100
             */
            total: number;
            /** @description Receiving rows matching the query */
            list: components["schemas"]["ReceivingPreviewSchema"][];
        };
        ReceivingQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
        };
        ReceivingOptionSchema: {
            /**
             * @description Receiving record id
             * @example 1
             */
            id: number;
            /**
             * @description Receiving date
             * @example 2026-04-28
             */
            name: string;
        };
        ReceivingTemplateItemSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Expected quantity in grams
             * @example 15000
             */
            expected_quantity: number;
            /**
             * @description Actual quantity in grams
             * @example 15000
             */
            actual_quantity: number;
        };
        ReceivingTemplateSchema: {
            /**
             * @description Procurement record id
             * @example 1
             */
            procurement_id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            target_date: string;
            /**
             * @description Receiving status
             * @example PENDING
             */
            status: string;
            /** @description Receiving template items */
            items: components["schemas"]["ReceivingTemplateItemSchema"][];
        };
        ReceivingCreateItemSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Actual received quantity in grams
             * @example 10000
             */
            actual_quantity: number;
            /**
             * @description Item notes
             * @example
             */
            notes?: string;
        };
        ReceivingUpsertSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Procurement id
             * @example 1
             */
            procurement_id: number;
            /**
             * @description Receiving notes
             * @example
             */
            notes?: string;
            /** @description Received items */
            items: components["schemas"]["ReceivingCreateItemSchema"][];
        };
        ReceivingUpdateItemSchema: {
            /**
             * @description Receiving item id
             * @example 1
             */
            id: number;
            /**
             * @description Actual received grams
             * @example 10000
             */
            actual_received_g: number | null;
            /**
             * @description Actual received supplier units
             * @example null
             */
            actual_received_special_unit?: number | null;
        };
        ReceivingUpdateSchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /** @description Receiving item updates */
            items: components["schemas"]["ReceivingUpdateItemSchema"][];
        };
        ProcessingItemSchema: {
            /**
             * @description Material id
             * @example 1
             */
            material_id: number;
            /**
             * @description Material name
             * @example Rice
             */
            material_name: string;
            /**
             * @description Material category
             * @example Grains
             */
            category: string;
            /**
             * @description Processing method
             * @example washed
             */
            processing_method: string;
            /**
             * @description Required processing quantity
             * @example 12.5
             */
            processing_requirement: number;
            /**
             * @description Processing time
             * @example
             */
            processing_time: string;
        };
        ProcessingQuerySchema: {
            /**
             * @description Date for the request
             * @example 2026-04-28
             */
            date?: string;
            /**
             * @description Company id
             * @example 1
             */
            company_id?: number;
            /**
             * @description Name filter
             * @example rice
             */
            name?: string;
            /**
             * @description Column name to sort by
             * @example name
             */
            sort_by?: string;
            /**
             * @description Sort order
             * @example desc
             * @enum {string}
             */
            sort_order?: "asc" | "desc";
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Page size
             * @example 50
             */
            page_size?: number;
            /**
             * @description Material id
             * @example 1
             */
            material_id?: number;
        };
        ProcessingOrderSchema: {
            /**
             * @description Processing order id
             * @example 1
             */
            id: number;
            /**
             * @description Target date
             * @example 2026-04-28
             */
            target_date: string;
            /**
             * @description Processing order status
             * @example DRAFT
             */
            status: string;
        };
        HealthResponseDto: {
            /** @example ok */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ApiErrorDto = components['schemas']['ApiErrorDto'];
export type ApiResponseDto = components['schemas']['ApiResponseDto'];
export type ApiListResultDto = components['schemas']['ApiListResultDto'];
export type CompanyPreviewSchema = components['schemas']['CompanyPreviewSchema'];
export type CompanyListResponseSchema = components['schemas']['CompanyListResponseSchema'];
export type CompanyQuerySchema = components['schemas']['CompanyQuerySchema'];
export type CompanyOptionSchema = components['schemas']['CompanyOptionSchema'];
export type CompanyRegionSchema = components['schemas']['CompanyRegionSchema'];
export type CompanyDetailSchema = components['schemas']['CompanyDetailSchema'];
export type CompanyRegionUpsertSchema = components['schemas']['CompanyRegionUpsertSchema'];
export type CompanyUpsertSchema = components['schemas']['CompanyUpsertSchema'];
export type IdResponseSchema = components['schemas']['IdResponseSchema'];
export type CompanyRegionOptionSchema = components['schemas']['CompanyRegionOptionSchema'];
export type StaplePreviewSchema = components['schemas']['StaplePreviewSchema'];
export type StapleListResponseSchema = components['schemas']['StapleListResponseSchema'];
export type StapleQuerySchema = components['schemas']['StapleQuerySchema'];
export type StapleOptionSchema = components['schemas']['StapleOptionSchema'];
export type StapleDetailSchema = components['schemas']['StapleDetailSchema'];
export type StapleUpsertSchema = components['schemas']['StapleUpsertSchema'];
export type MaterialProcessingMethodSchema = components['schemas']['MaterialProcessingMethodSchema'];
export type MaterialPreviewSchema = components['schemas']['MaterialPreviewSchema'];
export type MaterialListResponseSchema = components['schemas']['MaterialListResponseSchema'];
export type MaterialQuerySchema = components['schemas']['MaterialQuerySchema'];
export type MaterialOptionSchema = components['schemas']['MaterialOptionSchema'];
export type MaterialDetailSchema = components['schemas']['MaterialDetailSchema'];
export type MaterialUpsertSchema = components['schemas']['MaterialUpsertSchema'];
export type MaterialCategoryOptionSchema = components['schemas']['MaterialCategoryOptionSchema'];
export type DietPreviewSchema = components['schemas']['DietPreviewSchema'];
export type DietQuerySchema = components['schemas']['DietQuerySchema'];
export type DietOptionSchema = components['schemas']['DietOptionSchema'];
export type DietQuantitySchema = components['schemas']['DietQuantitySchema'];
export type DietMealSlotSchema = components['schemas']['DietMealSlotSchema'];
export type DietDetailSchema = components['schemas']['DietDetailSchema'];
export type DietCreateSchema = components['schemas']['DietCreateSchema'];
export type DietUpdateSchema = components['schemas']['DietUpdateSchema'];
export type DietMealSlotDishSchema = components['schemas']['DietMealSlotDishSchema'];
export type DietMealSlotUpsertSchema = components['schemas']['DietMealSlotUpsertSchema'];
export type DishIngredientSchema = components['schemas']['DishIngredientSchema'];
export type DishPreviewSchema = components['schemas']['DishPreviewSchema'];
export type DishListResponseSchema = components['schemas']['DishListResponseSchema'];
export type DishQuerySchema = components['schemas']['DishQuerySchema'];
export type DishOptionSchema = components['schemas']['DishOptionSchema'];
export type DishDetailSchema = components['schemas']['DishDetailSchema'];
export type DishIngredientUpsertSchema = components['schemas']['DishIngredientUpsertSchema'];
export type DishUpsertSchema = components['schemas']['DishUpsertSchema'];
export type SupplierMaterialPreviewSchema = components['schemas']['SupplierMaterialPreviewSchema'];
export type SupplierPreviewSchema = components['schemas']['SupplierPreviewSchema'];
export type SupplierListResponseSchema = components['schemas']['SupplierListResponseSchema'];
export type SupplierQuerySchema = components['schemas']['SupplierQuerySchema'];
export type SupplierOptionSchema = components['schemas']['SupplierOptionSchema'];
export type SupplierDetailSchema = components['schemas']['SupplierDetailSchema'];
export type SupplierUpsertSchema = components['schemas']['SupplierUpsertSchema'];
export type SupplierMaterialListResponseSchema = components['schemas']['SupplierMaterialListResponseSchema'];
export type SupplierMaterialQuerySchema = components['schemas']['SupplierMaterialQuerySchema'];
export type SupplierMaterialOptionSchema = components['schemas']['SupplierMaterialOptionSchema'];
export type SupplierMaterialDetailSchema = components['schemas']['SupplierMaterialDetailSchema'];
export type SupplierMaterialUpsertSchema = components['schemas']['SupplierMaterialUpsertSchema'];
export type CensusPreviewSchema = components['schemas']['CensusPreviewSchema'];
export type CensusListResponseSchema = components['schemas']['CensusListResponseSchema'];
export type CensusQuerySchema = components['schemas']['CensusQuerySchema'];
export type DatedMutationCountResponseSchema = components['schemas']['DatedMutationCountResponseSchema'];
export type CensusItemSchema = components['schemas']['CensusItemSchema'];
export type CensusUpsertSchema = components['schemas']['CensusUpsertSchema'];
export type ProcurementPreviewSchema = components['schemas']['ProcurementPreviewSchema'];
export type ProcurementListResponseSchema = components['schemas']['ProcurementListResponseSchema'];
export type ProcurementQuerySchema = components['schemas']['ProcurementQuerySchema'];
export type ProcurementRecordSchema = components['schemas']['ProcurementRecordSchema'];
export type DateCompanySchema = components['schemas']['DateCompanySchema'];
export type ProcurementUpdateItemSchema = components['schemas']['ProcurementUpdateItemSchema'];
export type ProcurementUpdateSchema = components['schemas']['ProcurementUpdateSchema'];
export type UpdatedCountResponseSchema = components['schemas']['UpdatedCountResponseSchema'];
export type ProcurementSupplierAssignmentSchema = components['schemas']['ProcurementSupplierAssignmentSchema'];
export type ProcurementAssignSuppliersSchema = components['schemas']['ProcurementAssignSuppliersSchema'];
export type ProcurementItemSchema = components['schemas']['ProcurementItemSchema'];
export type ProcurementSheetItemSchema = components['schemas']['ProcurementSheetItemSchema'];
export type ProcurementSheetSchema = components['schemas']['ProcurementSheetSchema'];
export type ReceivingPreviewSchema = components['schemas']['ReceivingPreviewSchema'];
export type ReceivingListResponseSchema = components['schemas']['ReceivingListResponseSchema'];
export type ReceivingQuerySchema = components['schemas']['ReceivingQuerySchema'];
export type ReceivingOptionSchema = components['schemas']['ReceivingOptionSchema'];
export type ReceivingTemplateItemSchema = components['schemas']['ReceivingTemplateItemSchema'];
export type ReceivingTemplateSchema = components['schemas']['ReceivingTemplateSchema'];
export type ReceivingCreateItemSchema = components['schemas']['ReceivingCreateItemSchema'];
export type ReceivingUpsertSchema = components['schemas']['ReceivingUpsertSchema'];
export type ReceivingUpdateItemSchema = components['schemas']['ReceivingUpdateItemSchema'];
export type ReceivingUpdateSchema = components['schemas']['ReceivingUpdateSchema'];
export type ProcessingItemSchema = components['schemas']['ProcessingItemSchema'];
export type ProcessingQuerySchema = components['schemas']['ProcessingQuerySchema'];
export type ProcessingOrderSchema = components['schemas']['ProcessingOrderSchema'];
export type HealthResponseDto = components['schemas']['HealthResponseDto'];
